# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blockchainlab DB
email: info@blockchainlab.it
description: > # this means to ignore newlines until "baseurl:"
  Blockchainlab Database
baseurl: "/jekyll-scalability-test" # the subpath of your site, e.g. /blog
url: "http://riccardo.casatta.it" # the base hostname & protocol for your site
twitter_username: blockchainlab
github_username:  blockchainlab

# Build settings
markdown: kramdown


github:
  repo: https://github.com/RCasatta/jekyll-scalability-test
  editpost: https://github.com/RCasatta/jekyll-scalability-test/edit/gh-pages/
